# config/component_dependencies.yaml
# Maps specific build tags to the Go module(s) they require.
# The build script uses this to run 'go edit' and then 'go tidy' for necessary dependencies
# only when the corresponding component is included in the build.
dependencies:
  # Build Tag: List of additional Go Module Paths
  # if not provided, the version will be appended based on the version of the collector
  lambdacomponents.exporter.clickhouse:
    - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter

  # AWS S3 exporter
  lambdacomponents.exporter.awss3:
    - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter

  # Signal to Metrics connector
  lambdacomponents.connector.signaltometrics:
    - github.com/open-telemetry/opentelemetry-collector-contrib/connector/signaltometricsconnector
    
  # Span Event to Log connector
  lambdacomponents.connector.spaneventtolog:
    - github.com/dev7a/otelcol-con-spaneventtolog@v0.6.0
  # AWS Secrets Manager Auth extension
  # Example of specifying a fixed version with @version syntax
  lambdacomponents.extension.asmauthextension:
    - github.com/dev7a/otelcol-ext-asmauth@v0.5.1

  # Add mappings for future custom components here
  # Examples:
  # lambdacomponents.processor.myprocessor:
  #   - github.com/some-org/some-module/v2  # Uses upstream version
  #   - github.com/another-org/another-module@v1.2.3  # Uses fixed version
