# Distribution definitions: name, description, base, and build tags
# Used by build_extension_layer.py, get_release_info.py and publish-custom-layer-collector.yml workflow
# The 'base' property allows inheriting buildtags from another distribution.

default:
  description: "Base upstream components"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.receiver.otlp
    - lambdacomponents.exporter.debug
    - lambdacomponents.exporter.otlp
    - lambdacomponents.exporter.otlphttp
    - lambdacomponents.processor.attributes
    - lambdacomponents.processor.filter
    - lambdacomponents.processor.memory_limiter
    - lambdacomponents.processor.probabilistic_sampler
    - lambdacomponents.processor.resource
    - lambdacomponents.processor.span
    - lambdacomponents.processor.decouple
    - lambdacomponents.processor.batch
    - lambdacomponents.extension.sigv4auth
    - lambdacomponents.extension.basicauth

full:
  description: "All available upstream and custom components"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.all

minimal:
  description: "OTLP receiver, Batch processor, Decouple processor, OTLP/HTTP exporter"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.receiver.otlp
    - lambdacomponents.processor.batch
    - lambdacomponents.processor.decouple
    - lambdacomponents.exporter.otlphttp

minimal-clickhouse:
  description: "Minimal + ClickHouse exporter"
  base: minimal
  buildtags:
    - lambdacomponents.exporter.clickhouse

minimal-s3export:
  description: "Minimal + AWS S3 exporter"
  base: minimal
  buildtags:
    - lambdacomponents.exporter.awss3


minimal-forwarder:
  description: "Minimal + Span Event to Log connector + AWS Secrets Manager Auth extension + Signal to Metrics connector"
  base: minimal
  config-file: forwarder.yaml
  buildtags:
    - lambdacomponents.connector.spaneventtolog
    - lambdacomponents.extension.asmauthextension
    - lambdacomponents.connector.signaltometrics

