# Distribution definitions: name, description, base, and build tags
# Used by build_extension_layer.py, get_release_info.py and publish-custom-layer-collector.yml workflow
# The 'base' property allows inheriting buildtags from another distribution.

default:
  description: "Standard upstream components (explicit)"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.receiver.otlp
    - lambdacomponents.receiver.telemetryapi
    - lambdacomponents.exporter.debug
    - lambdacomponents.exporter.otlp
    - lambdacomponents.exporter.otlphttp
    - lambdacomponents.exporter.prometheusremotewrite
    - lambdacomponents.processor.attributes
    - lambdacomponents.processor.filter
    - lambdacomponents.processor.memory_limiter
    - lambdacomponents.processor.probabilistic_sampler
    - lambdacomponents.processor.resource
    - lambdacomponents.processor.span
    - lambdacomponents.processor.coldstart
    - lambdacomponents.processor.decouple
    - lambdacomponents.processor.batch
    - lambdacomponents.extension.sigv4auth
    - lambdacomponents.extension.basicauth

full:
  description: "All available upstream and custom components"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.all
  config-file: full.yaml

minimal:
  description: "OTLP receiver, Batch processor, Decouple processor, OTLP/HTTP exporter"
  buildtags:
    - lambdacomponents.custom
    - lambdacomponents.receiver.otlp
    - lambdacomponents.processor.batch
    - lambdacomponents.processor.decouple
    - lambdacomponents.exporter.otlphttp
  config-file: minimal.yaml

clickhouse:
  description: "Minimal + ClickHouse exporter"
  base: minimal
  buildtags:
    - lambdacomponents.exporter.clickhouse
  config-file: clickhouse.yaml

exporters:
  description: "Distribution with all exporters and minimal components"
  base: minimal
  buildtags:
    - lambdacomponents.exporter.all
  config-file: exporters.yaml

s3export:
  description: "Minimal + AWS S3 exporter"
  base: minimal
  buildtags:
    - lambdacomponents.exporter.awss3
  config-file: s3export.yaml

asmauthextension:
  description: "Default + AWS Secrets Manager Auth extension"
  base: default
  buildtags:
    - lambdacomponents.extension.asmauthextension
  config-file: asmauthextension.yaml

signaltometrics:
  description: "Minimal + Signal to Metrics connector"
  base: minimal
  buildtags:
    - lambdacomponents.connector.signaltometrics
  config-file: signaltometrics.yaml
