extensions:
  asmauthextension:
    secret_name: "otel/vendor/auth-headers"
    region: "us-east-1"

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: ${env:OTLPHTTP_ENDPOINT}
    auth:
      authenticator: asmauthextension

service:
  extensions: [asmauthextension]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
