receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
    send_batch_size: 8192

exporters:
  awss3:
    s3uploader:
      region: "${secretsmanager:otel/aws#region:-us-east-1}"
      s3_bucket: "${secretsmanager:otel/aws/s3#bucket}"
      s3_prefix: "lambda-telemetry"
      s3_partition: "hour"
      compression: "gzip"
      file_prefix: "otel"
      # Uncomment if needed:
      # role_arn: "${secretsmanager:otel/aws/iam#role-arn}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3] 