receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

exporters:
  otlphttp:
    endpoint: "${secretsmanager:otel/endpoints#metrics}"
    tls:
      insecure: false

connectors:
  signaltometrics:
    metrics_flush_interval: 15s
    dimensions:
      - name: service.name
      - name: operation
        default_value: unknown_operation
      - name: span.kind
        default_value: internal
      - name: status.code
        default_value: 0
    
    # Define metrics to be created from spans
    metrics:
      - name: latency
        description: The latency of each span
        unit: ms
        mode: delta

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [signaltometrics]
    metrics:
      receivers: [signaltometrics]
      processors: [batch]
      exporters: [otlphttp] 